In [1]:
__author__ = "Sibashis Chatterjee (sibashis1992@gmail.com)"

In [ ]:
from googleapiclient.discovery import build
import pprint
import requests

from my_secrets import *

IMAGES_TO_DOWNLOAD = 1000

# Usage example: https://github.com/googleapis/google-api-python-client/blob/main/samples/customsearch/main.py#L39
# API Doc: https://developers.google.com/custom-search/v1/reference/rest/v1/cse/list

# Google Developer console: https://console.cloud.google.com/apis/dashboard?project=iisc-cee-project
# Programable Search console: https://programmablesearchengine.google.com/controlpanel/all
service = build("customsearch", "v1", developerKey = search_api_key)

totalResults = 0;
startIndex = 0
# Once failed at index 201, retrying
# totalResults = 200
# startIndex = 200

# loop till <IMAGES_TO_DOWNLOAD> images are downloaded
while totalResults < IMAGES_TO_DOWNLOAD:
    
    res = (
        service.cse()
        .list(
            q = "covid+19+infected+lungs+x+ray",
            hl = "en-US",
            cx = programable_search_engine_id,
            searchType = "image",
            start = startIndex
        )
        .execute()
    )
    
    for item in res["items"]:
        
        pprint.pprint(item["fileFormat"] + " from " + item["link"])
        
        if item["image"]:
            
            totalResults = totalResults + 1
            
            fileExtension = item["fileFormat"].split("/")[1]
            fileName = "/content/scrapped_images/image_" + str(totalResults) + ".jpeg"
            print("Writing " + fileName + " of type " + item["fileFormat"] + " from " + item["link"])
            
            img_data = requests.get(item["link"]).content
            with open(fileName, "wb") as handler:
                handler.write(img_data)
    
    # If there is a next page, use the start index in next iteration of the loop, break out of the loop oitherwise
    if (res and res["queries"] and res["queries"]["nextPage"]):
        startIndex = res["queries"]["nextPage"][0]["startIndex"]
    else:
        break


Started giving error at startIndex >= 200
```
HttpError: <HttpError 400 when requesting https://customsearch.googleapis.com/customsearch/v1?q=covid%2B19%2Binfected%2Blungs%2Bx%2Bray&hl=en-US&cx=XXXXXXXXXXXXXX&searchType=image&start=200&key=YYYYYYYYYYYYYYYYYYY&alt=json returned "Request contains an invalid argument.". Details: "[{'message': 'Request contains an invalid argument.', 'domain': 'global', 'reason': 'badRequest'}]">
```

In [7]:
import tensorflow as tf

model = tf.keras.models.load_model("/content/cnn_model")

In [17]:
import requests

dataSource1 = "https://storage.googleapis.com/kaggle-data-sets/627146/1117472/bundle/archive.zip?X-Goog-Algorithm=GOOG4-RSA-SHA256&X-Goog-Credential=gcp-kaggle-com%40kaggle-161607.iam.gserviceaccount.com%2F20230421%2Fauto%2Fstorage%2Fgoog4_request&X-Goog-Date=20230421T222415Z&X-Goog-Expires=259200&X-Goog-SignedHeaders=host&X-Goog-Signature=6d9f63e3270bfc0f8537d14a142e644617d586ac9d013def87a307ae92ec252076aff97df73563b6ff982d04fd3de2cf1997220450b1578c0decd5843b5368d58987deaf3f4a83df104a95f93340808759efc4fd996821c511cf74861fcca7705891616282bbf0f70ab02ea1e2310fcbc2f68f2940be8728edceae4dd41c1d69ad763d712f1a2288b061b3d7658fc36bd7b8ca006667f91bd7db3a934cbd1929bc097f9ecdd4fcf4abb99a76a8cc8481b224391513808f05db2be77f967ae503d0ab71c1cfdd1272332ab6794356827850a343718f7514e9032ec5de160dbbcf18314e0d127106eb21628b111ecb3185df9f97aafe0862ff5c9e78d04cac1644"
zip_data1 = requests.get(dataSource1).content
with open("/content/data1.zip", "wb") as handler:
  handler.write(zip_data1)

In [18]:
import zipfile

with zipfile.ZipFile("/content/data1.zip", 'r') as zip_ref:
    zip_ref.extractall("/content/input-dataset/")

In [25]:
# First 100 images as Positive Tests

import shutil
import os
    
source_dir = '/content/scrapped_images'

# Positive Tests
target_dir = '/content/google-test-images/positive/Covid'    
for i in range (1, 101, 1):
    shutil.move(os.path.join(source_dir, "image_" + str(i) + ".jpeg"), target_dir)
  
# Negative Tests
target_dir = '/content/google-test-images/negative/Normal'    
for i in range (101, 151, 1):
    shutil.move(os.path.join(source_dir, "image_" + str(i) + ".jpeg"), target_dir)

target_dir = '/content/google-test-images/negative/Viral Pneumonia'    
for i in range (151, 201, 1):
    shutil.move(os.path.join(source_dir, "image_" + str(i) + ".jpeg"), target_dir)

In [46]:
test_data_dir = "/content/input-dataset/Covid19-dataset/test"
test_data_processor = tf.keras.preprocessing.image.ImageDataGenerator(rescale=1./255)
test_data_processed = test_data_processor.flow_from_directory(
    test_data_dir,
    target_size=(256, 256),
    batch_size=32,
    class_mode='categorical',
    classes=["Covid", "Normal", "Viral Pneumonia"])
model.evaluate(test_data_processed)

Found 66 images belonging to 3 classes.
3/3 [==============================] - 4s 712ms/step - loss: 0.4677 - accuracy: 0.8636


[0.4677329659461975, 0.8636363744735718]

In [49]:
# Sanitize the positive test case data
import os
from PIL import Image
folder_path = '/content/google-test-images/positive'
extensions = []
for fldr in os.listdir(folder_path):
  if not fldr.startswith('.'):
    sub_folder_path = os.path.join(folder_path, fldr)
    for filee in os.listdir(sub_folder_path):
      if not filee.startswith('.'):
        file_path = os.path.join(sub_folder_path, filee)
        print('** Path: {}  **'.format(file_path), end="\r", flush=True)
        im = Image.open(file_path)
        rgb_im = im.convert('RGB')
        if filee.split('.')[1] not in extensions:
            extensions.append(filee.split('.')[1])

```
UnidentifiedImageError: cannot identify image file '/content/google-test-images/positive/Covid/image_54.jpeg'
UnidentifiedImageError: cannot identify image file '/content/google-test-images/positive/Covid/image_59.jpeg'
UnidentifiedImageError: cannot identify image file '/content/google-test-images/positive/Covid/image_21.jpeg'
```

In [71]:
# Sanitize the positive test case data
import os
from PIL import Image
folder_path = '/content/google-test-images/negative'
extensions = []
for fldr in os.listdir(folder_path):
  if not fldr.startswith('.'):
    sub_folder_path = os.path.join(folder_path, fldr)
    for filee in os.listdir(sub_folder_path):
      if not filee.startswith('.'):
        file_path = os.path.join(sub_folder_path, filee)
        print('** Path: {}  **'.format(file_path), end="\r", flush=True)
        im = Image.open(file_path)
        rgb_im = im.convert('RGB')
        if filee.split('.')[1] not in extensions:
            extensions.append(filee.split('.')[1])

```
UnidentifiedImageError: cannot identify image file '/content/google-test-images/negative/Viral Pneumonia/image_177.jpeg'
UnidentifiedImageError: cannot identify image file '/content/google-test-images/negative/Viral Pneumonia/image_175.jpeg'
UnidentifiedImageError: cannot identify image file '/content/google-test-images/negative/Viral Pneumonia/image_183.jpeg'
UnidentifiedImageError: cannot identify image file '/content/google-test-images/negative/Viral Pneumonia/image_185.jpeg'
UnidentifiedImageError: cannot identify image file '/content/google-test-images/negative/Viral Pneumonia/image_169.jpeg'
UnidentifiedImageError: cannot identify image file '/content/google-test-images/negative/Viral Pneumonia/image_166.jpeg'
UnidentifiedImageError: cannot identify image file '/content/google-test-images/negative/Viral Pneumonia/image_192.jpeg'
UnidentifiedImageError: cannot identify image file '/content/google-test-images/negative/Viral Pneumonia/image_183.jpeg'
UnidentifiedImageError: cannot identify image file '/content/google-test-images/negative/Viral Pneumonia/image_173.jpeg'
UnidentifiedImageError: cannot identify image file '/content/google-test-images/negative/Viral Pneumonia/image_162.jpeg'
UnidentifiedImageError: cannot identify image file '/content/google-test-images/negative/Viral Pneumonia/image_154.jpeg'
UnidentifiedImageError: cannot identify image file '/content/google-test-images/negative/Viral Pneumonia/image_190.jpeg'
UnidentifiedImageError: cannot identify image file '/content/google-test-images/negative/Viral Pneumonia/image_155.jpeg'
UnidentifiedImageError: cannot identify image file '/content/google-test-images/negative/Normal/image_127.jpeg'
UnidentifiedImageError: cannot identify image file '/content/google-test-images/negative/Normal/image_144.jpeg'
UnidentifiedImageError: cannot identify image file '/content/google-test-images/negative/Normal/image_147.jpeg'
UnidentifiedImageError: cannot identify image file '/content/google-test-images/negative/Normal/image_138.jpeg'
UnidentifiedImageError: cannot identify image file '/content/google-test-images/negative/Normal/image_129.jpeg'
UnidentifiedImageError: cannot identify image file '/content/google-test-images/negative/Normal/image_136.jpeg'
UnidentifiedImageError: cannot identify image file '/content/google-test-images/negative/Normal/image_120.jpeg'
```

In [72]:
# Read Positive Test Cases
google_images_positive_data_dir =  "/content/google-test-images/positive"
google_images_positive_data_processor = tf.keras.preprocessing.image.ImageDataGenerator(rescale=1./255)
google_images_positive_data_processed = google_images_positive_data_processor.flow_from_directory(
    google_images_positive_data_dir,
    target_size=(256, 256),
    batch_size=32,
    class_mode='categorical',
    classes=["Covid", "Normal", "Viral Pneumonia"])

Found 97 images belonging to 3 classes.


In [73]:
google_images_positive_data_processed.classes

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int32)

In [74]:
# Predict Positive Cases
predicted = model.predict(google_images_positive_data_processed)

4/4 [==============================] - 8s 2s/step


In [78]:
import numpy as np
positive_test_case_results = np.argmax(predicted, axis = 1)

In [77]:
model.evaluate(google_images_positive_data_processed)

4/4 [==============================] - 9s 2s/step - loss: 0.9084 - accuracy: 0.8041


[0.9083557724952698, 0.8041236996650696]

In [79]:
positive_test_case_results

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 1,
       2, 0, 0, 0, 0, 0, 2, 0, 2, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 2,
       0, 0, 0, 1, 0, 2, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 2, 0, 2, 0, 0, 0, 0, 0, 2, 0, 2,
       0, 2, 1, 0, 0, 2, 0, 0, 0])

In [111]:
totalCases = 0
correct = 0
falseNormal = 0
falsePneumonia = 0
invalidPrediction = 0

print ("Negative predictions: ", positive_test_case_results.shape)

for positive_case in positive_test_case_results.flat:
    totalCases = totalCases + 1
    if positive_case == 0:
      correct = correct + 1
    elif positive_case == 1:
      falseNormal = falseNormal + 1
    elif positive_case == 2:
      falsePneumonia = falsePneumonia + 1
    else:
      invalidPrediction = invalidPrediction + 1

print ("Positive Test cases:")
print ("  Total Predictions = ", totalCases)
print ("  Correct Predictions = ", correct, " that is ", (correct/totalCases*100), "% of all predictions")
print ("  Falsely Predicted as Normal = ", falseNormal, " that is ", (falseNormal/totalCases*100), "% of all predictions")
print ("  Falsely Predicted as Pneumonia  = ", falsePneumonia, " that is ", (falsePneumonia/totalCases*100), "% of all predictions")
print ("  Invalid Predictions = ", invalidPrediction, " that is ", (invalidPrediction/totalCases*100), "% of all predictions")

Negative predictions:  (97,)
Positive Test cases:
  Total Predictions =  97
  Correct Predictions =  78  that is  80.41237113402062 % of all predictions
  Falsely Predicted as Normal =  5  that is  5.154639175257731 % of all predictions
  Falsely Predicted as Pneumonia  =  14  that is  14.432989690721648 % of all predictions
  Invalid Predictions =  0  that is  0.0 % of all predictions


In [112]:
# Read Negative Test Cases
google_images_negative_data_dir =  "/content/google-test-images/negative"
google_images_negative_data_processor = tf.keras.preprocessing.image.ImageDataGenerator(rescale=1./255)
google_images_negative_data_processed = google_images_negative_data_processor.flow_from_directory(
    google_images_negative_data_dir,
    target_size=(256, 256),
    batch_size=32,
    class_mode='categorical',
    classes=["Covid", "Normal", "Viral Pneumonia"])

Found 80 images belonging to 3 classes.


In [113]:
google_images_negative_data_processed.classes

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2], dtype=int32)

In [114]:
# Predict Negative Cases
predicted_neg = model.predict(google_images_negative_data_processed)

3/3 [==============================] - 5s 978ms/step


In [115]:
import numpy as np
negative_test_case_results = np.argmax(predicted_neg, axis = 1)

In [116]:
model.evaluate(google_images_negative_data_processed)

3/3 [==============================] - 5s 1s/step - loss: 17.8422 - accuracy: 0.0750


[17.842172622680664, 0.07500000298023224]

In [117]:
negative_test_case_results

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 1, 0, 0, 0, 0, 2, 1, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 2, 2, 0, 0, 0, 0, 0, 0, 1, 0, 0, 2, 2, 0, 0, 0,
       2, 2, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [119]:
totalCases = 0
correct = 0
falseNormal = 0
falsePneumonia = 0
invalidPrediction = 0

print ("Negative predictions: ", negative_test_case_results.shape)

for negative_case in negative_test_case_results.flat:
  totalCases = totalCases + 1
  if negative_case == 0:
    correct = correct + 1
  elif negative_case == 1:
    falseNormal = falseNormal + 1
  elif negative_case == 2:
    falsePneumonia = falsePneumonia + 1
  else:
    invalidPrediction = invalidPrediction + 1

print ("Positive Test cases:")
print ("  Total Predictions = ", totalCases)
print ("  Correct Predictions = ", correct, " that is ", (correct/totalCases*100), "% of all predictions")
print ("  Falsely Predicted as Normal = ", falseNormal, " that is ", (falseNormal/totalCases*100), "% of all predictions")
print ("  Falsely Predicted as Pneumonia  = ", falsePneumonia, " that is ", (falsePneumonia/totalCases*100), "% of all predictions")
print ("  Invalid Predictions = ", invalidPrediction, " that is ", (invalidPrediction/totalCases*100), "% of all predictions")

Negative predictions:  (80,)
Positive Test cases:
  Total Predictions =  80
  Correct Predictions =  64  that is  80.0 % of all predictions
  Falsely Predicted as Normal =  7  that is  8.75 % of all predictions
  Falsely Predicted as Pneumonia  =  9  that is  11.25 % of all predictions
  Invalid Predictions =  0  that is  0.0 % of all predictions
